sudo: false
language: scala
scala:
- 2.12.3
script:
- sbt ++$TRAVIS_SCALA_VERSION coverage test
jdk:
- oraclejdk8
after_success:
- bash <(curl -s https://codecov.io/bash)
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then sbt ++2.13.1 releaseEarly;sbt ++2.12.7 releaseEarly;
  fi

before_install:
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then openssl aes-256-cbc -K $encrypted_474c3e42cec4_key
  -iv $encrypted_474c3e42cec4_iv -in travis/secrets.tar.enc -out travis/secrets.tar
  -d; tar xv -C travis -f travis/secrets.tar; fi
env:
  global:
  - secure: hWGHJQpRJGUXybiS9Jrp+06aIaMgbxGwh4i28q7VkNvIq+bnT8TPVzHZNa8up1k1girM/bd8Z9q/qndZYAMJpowtxnre7+EnxnoFqeF8+Er6jrGG98EwVnX5h2/0r8lDDQqRejQsg2VF8JJnJk6ursc9gyuqQWqVGraTIaBXPjAPt+VOCViS+XP1r1v3ORWpjhOU6X0H+U3EIWRrzLQYRPOeFpqbA3WN8a09ZurglKuSb+F44Zz/4vm6+WXydXAX0Na7J9znBTghB/FPED+cIk9jSP4y9yMYetOXbpFIchzfzEcTFMZjX0IGOgPD2mBznDloWLuL1c169jyUS8MCl/FWYKL5SXnXhDMcpC1sEbXhP8W4xkdb0GSkP6NpYI1Wp7zlbGnsOMise5OuNEXH/ELHDLcqp2u4Ybb9MfiI8yxViFGQWUVHz/CgpHENsWi/pb3XsHaCYZtOFmyQUmK4vpeQs3eFtUBFZnvSIqKskThc6Yigah8GMMl9p2UPbZ0lQ6DL+XgveJzXAX7UYL3yp6EZdKPoofEP8PxXCSkJ9VMHnlOFXXEunQTET3nXNuLtRTyO+l6yC1EPcak0yiJGDLoW0eBGtkq3jbMK1i5ksbLNS14DmhD8g1CtPKDzbXBxlV7sPpLlEX7mNzCz2iSrI75zee6CC8pBH31smO/9F5E=
  - secure: Ru5PHdTXQysRUo/TU8QP863/wYRdj+IShm8HhQNGK9uYixPcf8Gd7ZjddgRVLmnkDBg+4ensKHddYYSFPwVbKoky+UL71LOP9WWrQuHY7UgFrLzzMdrTUNenrUxnAhKytx+iksuhRlGiw4lNAsXRniu8vDdDazaAgZ15tYpeK03T77dINupUuazvbDSMgPO2SpoMzDBJy6VIz8RAc+7UGrvSyvbsoq/p+Ep9ov+RVNOsX5If7sSiRzs8n+Se8eYYggjoBRVL5Guz0XhsayZ9CC2eua+XqCyXhhlVdalZJmQsOLP61IaNl9v73g75VROn8ayXCRnNsNTl1hDH5rLSi9jJVHIjjSnTm7w3qiADqP6t8HqAabi+QPAEnBR4LE7az24wW9YsDaftBJX1zoIOWWcKRG4s9FwyMrI0JcUYgh6K40SbX7dKTCKzO6UczyitRAVh99MnZPdW7ZGxrpObNH7FEXQXWcYcT5sF/oDoPc5c334KJRlcpGCldY8f7l7ulZjAFtvSgFawvDJrjdRdWXlNz/ApCrToTpshLYSX4+FYr93oHkWejfp43dJqHAqkDoV4xHXTYWrOGOeWsnE83XuOVpniUo1no4vaUSCbN7iVM0Hgah4BRVAZtKg4WrDL2Gz2AuKRRcv59sJsOguajHNtZ1ZGF6nCY9v1XIUrKsk=
  - secure: pqQHiCDZgtGl15utG6P63Gm8w8rrg1aSg3QwqWyVDTonp0hW0fNEoNMpRZUjuk9CkiS9nUiNdecVlJtWDzl0ObWXu8hO0tUPw9iS2QECkoa1ouQD8LV9oiBuFYv6XtWSGHWA5uI8bsUIHGCMfB0Kah9U8UxkuSzKTZ/zfqFpVF+MLQ3vwG9LxXbdZaAegvnFyt90hB8IgVFyJusE0YFp3jO8vtxl+ZJCSAPkk0d8v9v3EcGCnZPRN/L24AMT0mX+QPgowVOmlo4Do0HPtYWeh8elVBXpWnJ0+pLHh5LuIsNanP1FSSapzYFpshybXmvM4JUvPfJHGYTtRBA1Xh88rqsrd6MwQy0iKNXX8NsRM4ryR9hgszfI3Qc/uTg2LbyNfbnCxe/ZVLEducy2VRp/5QUrktaeFZkzGD/nobwWW0uj/W0lPOV9VBTLXrfgjOgtw06crUgKiCnRSRvirrWF7VGlkhDFsfotO1PzjC5VLtc44nQqsGOwOitSzKspwsP4iwpIo/wfR7JAeWycxDRA9yizO9uij30LQvSRKd4rdcTdXBx0/ymyi8nw1soka4lu2GxsarolsPLVLliEmaLT1sR4Jseoki3Mv6sun1XF++SiKr0Rkd1IA3uBc4cRzNtwf4tcvtJ2AYzozTjg1yD33oFk6zRCiFD1fgtwEpOqshE=
